---
swagger: '2.0'
info:
  version: 1.0.5
  title: Pizza Slicer API
  description: With this API you can predict how many slices you need to cut your
    pizza for a given crowd.
  contact:
    name: Awesome startup
    url: http://www.awesomestartup.be
    email: joe@awesomestartup.be
host: "{{host}}"
basePath: "/{{domain}}/{{apiname}}/{{apiversion}}"
schemes:
- "https"
paths:
  "/pizzas":
    post:
      summary: Add a pizza to the party
      description: You can add as many pizza's to the party as you want. Be sure to
        waste no food however.
      produces:
      - application/json
      parameters:
      - "$ref": "#/parameters/apikeyParam"
      - "$ref": "#/parameters/tenantParam"
      responses:
        '201':
          description: Pizza added
  pizzas/{pizzaId}:
    get:
      summary: Get the pizza by Id
      description: Retrieve the flavor, size and awesomeness of the pizza that we've
        numbered for you.
      produces:
      - application/json
      parameters:
      - name: pizzaId
        description: The number on the side of the pizzabox
        in: path
        required: true
        type: string
      - "$ref": "#/parameters/apikeyParam"
      - "$ref": "#/parameters/tenantParam"
      responses:
        '200':
          description: Ok
  pizzas/{pizzaId}/slice:
    put:
      summary: Slices the pizza
      description: Ready to dive in? Slice the pizza and distribute the pieces.
      produces:
      - application/json
      parameters:
      - name: pizzaId
        description: The number on the side of the pizzabox
        in: path
        required: true
        type: string
      - "$ref": "#/parameters/apikeyParam"
      - "$ref": "#/parameters/tenantParam"
      responses:
        '200':
          description: Ok
parameters:
  apikeyParam:
    name: apikey
    description: from a contract in the api store
    in: header
    required: true
    type: string
  tenantParam:
    name: tenant
    description: the name of the tenant you want to use
    in: header
    required: true
    type: string
